### ISSUE TITLE
The code contains invalid names

### ISSUE THREAD

**Issue by acc-to-learn** [timmahrt/pyAcoustics#1]
openTextGrid:
https://github.com/timmahrt/pyAcoustics/blob/master/examples/estimate_speech_rate.py#L100
openTextgrid:
https://github.com/timmahrt/praatIO/blob/master/praatio/tgio.py#L1404

**Comment by timmahrt** [comment]
Hey, thanks for the heads up.  I have updated estimate_speech_rate so that it is sync with recent changes I made to tgio.  I unfortunately don't have matlab anymore so I can't test estimate_speech_rate.py.

If you encounter any other problems, please let me know.
