### ISSUE TITLE
Adding mp3 format and multi-channel

### ISSUE THREAD

**Issue by acc-to-learn** [timmahrt/pyAcoustics#2]

**Comment by timmahrt** [comment]
Adding mp3 format and multi-channel support to what?  pyAcoustics is a collection of related (but separate) scripts.  It is feasible to rely on some audio-format-neutral io system but I don't have plans to implement something like that any time soon.  

Opening an mp3 file would require ffmpeg--of which there are many python wrappers already available.

Multi-channel support is more complicated.  How should certain scripts act when there are multiple channels?

Is there a specific task you are trying to do or you are just looking for pyAcoustics to be more flexible?

**Comment by acc-to-learn** [comment]
Yes, I'm trying to do a specific task - to estimate the speech of interlocutors call-center.
Ok, got it, thanks for your answer!

**Comment by timmahrt** [comment]
For the moment, I won't be adding this functionality to the code.  I recommend using sox or audacity to first sanitize the input:

sox input.mp3 output.wav channels 1

sox can easily be scripted (even by python) and audacity has 'chains' which enables one to automate tasks for batch processing from within the user interface.  Would that work for your purposes?
