### ISSUE TITLE
where is praat_pi.py?

### ISSUE THREAD

**Issue by bhomass** [timmahrt/pyAcoustics#3]
README mentions pyacoustics.intensity_and_pitch.praat_pi.getPraatPitchAndIntensity(), but there is no praat_pi.py file in that folder. Does someone need to check it in?

**Comment by timmahrt** [comment]
Hello Bruce,
Sorry, that is outdated documentation.  It is referring to my library
praatio.

What are you trying to do with pyacoustics?  Much of the functionality of
pyacoustics was moved to praatio.

Even if the documentation is outdated, I *think* the pyacoustics code has
been mostly refactored to reflect the changes to praatio.

I'll update the documentation this week.  Thanks!

Sorry for the inconvenience,
Tim

**Comment by bhomass** [comment]
Ok, I see the pitch_and_intensity.py file over in praatio. Thanks.
