### ISSUE TITLE
speech segmentation without create file

### ISSUE THREAD

**Issue by wahyubram82** [timmahrt/pyAcoustics#4]
i want to analyze every segment of speech without creating file...

i try to make a segmentation of speech with yout script.

```
from pyacoustics.signals import audio_scripts as ascr
wavfile = 'D:/Temp/speech/test.wav'
duration = ascr.getSoundFileDuration(wavfile)
splitwav = ascr.getSubwav(wavfile, 0, duration, True)

```
the next step should be get the data for every segment.
can you help me to do that?

**Comment by timmahrt** [comment]
What data are you trying to collect?  Where are your segments defined?

**Comment by timmahrt** [comment]
I'm closing this since there hasn't been any activity for a while.  If you have any more questions, please feel free to reopen.
